import img1 from '/products/belysning/lampa1.webp';
import img2 from '/products/belysning/lampa2.webp';
import img3 from '/products/belysning/lampa3.webp';
import img4 from '/products/belysning/ljusslinga1.webp';
import img5 from '/products/belysning/ljusslinga2.webp';
import img6 from '/products/kuddar/pillow102.jpg';
import img7 from '/products/kuddar/pillow103.webp';
import img8 from '/products/kuddar/pillow104.webp';
import img9 from '/products/kuddar/pillow105.webp';
import img10 from '/products/kuddar/pillow106.webp';
import img11 from '/products/kuddar/pillow107.webp';
import img12 from '/products/kuddar/pillow108.webp';

//product array
export const products = [
  {
    name: 'Tomte vit/grå',
    id: 0,
    price: 149,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img1],
    alt: 'tomte i grått och vitt tyg stor spetsig mössa',
    description: 'Mysig tygtomte med fuskpäls',
    category: ['dekoration', 'alla'],
  },
  {
    name: 'Veteranbil med tomte',
    id: 1,
    price: 299,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img2],
    alt: 'veteranbil med tomte, i grönt och svart porslin',
    description: 'Fin veteranbil med tomte, i porslin.',
    category: ['dekoration', 'alla'],
  },
  {
    name: 'Svamplykta',
    id: 2,
    price: 129,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img3],
    alt: 'svampformad ljuslykta i keramik',
    description: 'Gullig svampformad ljuslykta i keramik',
    category: ['dekoration', 'belysning', 'alla'],
  },
  {
    name: 'Ljusstake vit',
    id: 3,
    price: 79,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img4],
    alt: 'Ljusstake i vit keramik för 5 ljus',
    description: 'Ljusstake i vit keramik för 5 ljus',
    category: ['belysning', 'dekoration', 'alla'],
  },
  {
    name: 'Ljusstake grå betong',
    id: 4,
    price: 499,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img5],
    alt: 'Ljusstake för 10 ljus i betong',
    description: 'Ljusstake för 10 ljus i betong',
    category: ['belysning', 'dekoration', 'alla'],
  },

  {
    name: 'Julstjärna röd',
    id: 5,
    price: 179,
    rating: 2,
    amount: 0,
    sum: 0,
    img: [img6],
    alt: 'Röd julstjärna 100 cm',
    description: 'Röd julstjärna 100 cm',
    category: ['belysning', 'alla'],
  },
  {
    name: 'Duk paisely',
    id: 6,
    price: 429,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img7],
    alt: 'Röd och beige paisely-mönstrad duk',
    description: 'Röd och beige paisely-mönstrad duk, 200 x 250 cm',
    category: ['tyger', 'alla'],
  },
  {
    name: 'Duk linne',
    id: 7,
    price: 249,
    rating: 2,
    amount: 0,
    sum: 0,
    img: [img8],
    alt: 'röd linneduk med vita och röda ränder i mitten',
    description: 'röd linneduk med vita och röda ränder i mitten',
    category: ['tyger', 'alla'],
  },
  {
    name: 'Filt i fuskpäls',
    id: 8,
    price: 1049,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img9],
    alt: 'filt i brun och vit fuskpäls, 70 x 150cm',
    description: 'Mysig filt i brun och vit fuskpäls, 70 x 150cm',
    category: ['tyger', 'alla'],
  },
  {
    name: 'Rutig filt i ull',
    id: 9,
    price: 649,
    rating: 1,
    amount: 0,
    sum: 0,
    img: [img10],
    alt: 'Röd och grårutig filt i tovad ull',
    description: 'Röd och grårutig filt i tovad ull',
    category: ['tyger', 'alla'],
  },
  {
    name: 'Kudde med tofsar',
    id: 10,
    price: 299,
    rating: 1,
    amount: 0,
    sum: 0,
    img: [img11],
    alt: 'mönstrad blå och röd kudde med tofsar i hörnen',
    description: 'mönstrad blå och röd kudde med tofsar i hörnen',
    category: ['tyger', 'alla'],
  },
  {
    name: 'Kudde i linne',
    id: 11,
    price: 149,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img12],
    alt: 'linnefärgad kudde med julmotiv',
    description: 'linnefärgad kudde med julmotiv',
    category: ['tyger', 'alla'],
  },
];
