//product array
const products = [
  {
    name: 'Tomte vit/grå',
    id: 0,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/tomte-vit-1.png'],
    alt: ['', ''],
    description: 'Mysig tygtomte med fuskpäls',
    category: ['dekoration', 'all'],
  },
  {
    name: 'Veteranbil',
    id: 1,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/tomtevagn-1.jpg', ''],
    alt: ['', ''],
    description: 'Fin veteranbil med tomte, i porslin.',
    category: ['dekoration', 'all'],
  },
  {
    name: 'Svamplykta',
    id: 2,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/tomtelykta-1.png', ''],
    alt: ['', ''],
    description: 'Gullig svampformad ljuslykta i keramik',
    category: ['dekoration', 'belysning', 'all'],
  },
  {
    name: 'Ljusstake vit keramik',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/ljusstake-vit-1.jpg', ''],
    alt: ['', ''],
    description: 'Ljusstake i vit keramik för 5 ljus',
    category: ['belysning', 'all'],
  },
  {
    name: 'Ljusstake grå betong',
    id: 4,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/ljusstake-gra-1.jpg', ''],
    alt: ['', ''],
    description: 'Ljusstake för 10 ljus i betong',
    category: ['dekoration', 'all'],
  },

  {
    name: 'Julstjärna röd',
    id: 5,
    price: 199,
    originalPrice: 199,
    rating: 5,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/julstjarna-1.png', ''],
    alt: ['', ''],
    description: 'Röd julstjärna 100 cm',
    category: ['dekoration', 'all'],
  },
  {
    name: 'Duk paisely',
    id: 6,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/julduk-paisely-1.png', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: 'Duk linne',
    id: 7,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/julduk-rand-1.png', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: 'Filt i fuskpäls',
    id: 8,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/filt-varg-1.jpg', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: 'Rutig filt i ull',
    id: 9,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/filt-rutig-1.jpg', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: 'Kudde med tofsar',
    id: 10,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/kudde-tofsar-1.jpg', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: 'Kudde i linne',
    id: 11,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/kudde-linne-1.jpg', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
];
