import img1 from '/products/belysning/lampa1.webp';
import img2 from '/products/belysning/lampa2.webp';
import img3 from '/products/belysning/lampa3.webp';
import img4 from '/products/belysning/ljusslinga1.webp';
import img5 from '/products/belysning/ljusslinga2.webp';
import img6 from '/products/kuddar/pillow102.jpg';
import img7 from '/products/kuddar/pillow103.webp';
import img8 from '/products/kuddar/pillow104.webp';
import img9 from '/products/kuddar/pillow105.webp';
import img10 from '/products/kuddar/pillow106.webp';
import img11 from '/products/kuddar/pillow107.webp';
import img12 from '/products/kuddar/pillow108.webp';
import img13 from '/products/dekorationer/bell.jpg';
import img14 from '/products/dekorationer/candycane.jpg';
import img15 from '/products/dekorationer/ornament.jpg';
import img16 from '/products/dekorationer/wreath.jpg';
import img17 from '/products/dekorationer/wreath2.webp';
import img18 from '/products/dekorationer/wreath3.webp';
import img19 from '/products/dekorationer/wreath4.webp';
import img20 from '/products/krukor/pot10.webp';
import img21 from '/products/krukor/pot11.webp';
import img22 from '/products/krukor/pot12.webp';
import img23 from '/products/krukor/pot13.webp';
import img24 from '/products/krukor/pot14.webp';
import img25 from '/products/krukor/pot15.webp';
import img26 from '/products/krukor/pot16.webp';
import img27 from '/products/leksaker/car.webp';
import img28 from '/products/leksaker/doll.webp';
import img29 from '/products/leksaker/robot.webp';
import img30 from '/products/leksaker/spinner.webp';
import img31 from '/products/leksaker/teddybear.webp';
import img32 from '/products/leksaker/teddybunny.webp';

export const products = [
  {
    name: 'Lampa gran',
    id: 0,
    price: 199,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img1],
    category: ['belysning', 'alla'],
  },
  {
    name: 'Lampa snöflinga',
    id: 1,
    price: 299,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img2],
    category: ['belysning', 'alla'],
  },
  {
    name: 'Lampa med klockformad fot',
    id: 2,
    price: 149,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img3],
    category: ['belysning', 'alla'],
  },
  {
    name: 'Ljusslinga inomhusbruk',
    id: 3,
    price: 89,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img4],
    category: ['belysning', 'alla'],
  },
  {
    name: 'Ljusslinga utomhusbruk',
    id: 4,
    price: 129,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img5],
    category: ['belysning', 'alla'],
  },
  {
    name: 'Kudde i linne',
    id: 5,
    price: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img6],
    category: ['tyger', 'alla'],
  },
  {
    name: 'Linnekudde med mönster',
    id: 6,
    price: 249,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img7],
    category: ['tyger', 'alla'],
  },
  {
    name: 'Kuddfodral',
    id: 7,
    price: 179,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img8],
    category: ['tyger', 'alla'],
  },
  {
    name: 'Kudde i linne med stjärnmotiv',
    id: 8,
    price: 299,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img9],
    category: ['tyger', 'alla'],
  },
  {
    name: 'Julig kudde med broderi',
    id: 9,
    price: 159,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img10],
    category: ['tyger', 'alla'],
  },
  {
    name: 'Röd kudde med broderi',
    id: 10,
    price: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img11],
    category: ['tyger', 'alla'],
  },
  {
    name: 'Röd kudde med tryck',
    id: 11,
    price: 279,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img12],
    category: ['tyger', 'alla'],
  },
  {
    name: 'Dekoration till granen',
    id: 12,
    price: 99,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img13],
    category: ['dekoration', 'alla'],
  },
  {
    name: 'Godiskäpp i plast för granen',
    id: 13,
    price: 69,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img14],
    category: ['dekoration', 'alla'],
  },
  {
    name: 'Julgranskula',
    id: 14,
    price: 49,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img15],
    category: ['dekoration', 'alla'],
  },
  {
    name: 'Dekorationskrans till dörren.',
    id: 15,
    price: 249,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img16],
    category: ['dekoration', 'alla'],
  },
  {
    name: 'Dekorationskrans till dörren.',
    id: 16,
    price: 199,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img17],
    category: ['dekoration', 'alla'],
  },
  {
    name: 'Dekorationskrans till dörren.',
    id: 17,
    price: 179,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img18],
    category: ['dekoration', 'alla'],
  },
  {
    name: 'Dekorationskrans till dörren.',
    id: 18,
    price: 229,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img19],
    category: ['dekoration', 'alla'],
  },
  {
    name: 'Kruka',
    id: 19,
    price: 149,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img20],
    category: ['krukor', 'alla'],
  },
  {
    name: 'Kruka',
    id: 20,
    price: 199,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img21],
    category: ['krukor', 'alla'],
  },
  {
    name: 'Kruka',
    id: 21,
    price: 179,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img22],
    category: ['krukor', 'alla'],
  },
  {
    name: 'Kruka',
    id: 22,
    price: 129,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img23],
    category: ['krukor', 'alla'],
  },
  {
    name: 'Kruka',
    id: 23,
    price: 189,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img24],
    category: ['krukor', 'alla'],
  },
  {
    name: 'Kruka',
    id: 24,
    price: 209,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img25],
    category: ['krukor', 'alla'],
  },
  {
    name: 'Kruka',
    id: 25,
    price: 149,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img26],
    category: ['krukor', 'alla'],
  },
  {
    name: 'Leksaksbil',
    id: 26,
    price: 99,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img27],
    category: ['leksaker', 'alla'],
  },
  {
    name: 'Docka',
    id: 27,
    price: 199,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img28],
    category: ['leksaker', 'alla'],
  },
  {
    name: 'Robot',
    id: 28,
    price: 599,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img29],
    category: ['leksaker', 'alla'],
  },
  {
    name: 'Spinner',
    id: 29,
    price: 49,
    rating: 3,
    amount: 0,
    sum: 0,
    img: [img30],
    category: ['leksaker', 'alla'],
  },
  {
    name: 'Teddybjörn',
    id: 30,
    price: 299,
    rating: 5,
    amount: 0,
    sum: 0,
    img: [img31],
    category: ['leksaker', 'alla'],
  },
  {
    name: 'Mjukis kanin',
    id: 31,
    price: 349,
    rating: 4,
    amount: 0,
    sum: 0,
    img: [img32],
    category: ['leksaker', 'alla'],
  },
];
