// import './style/style.scss';
const hamburgerButton = document.querySelector('.hamburger-menu-icon');
hamburgerButton.addEventListener('click', toggleHamburger);
function toggleHamburger(event) {
  event.currentTarget.classList.toggle('change');
}
//producy array
const products = [
  {
    name: 'Tomte vit/grå',
    id: 0,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/tomte-vit-1.png'],
    alt: ['', ''],
    description: 'Mysig tygtomte med fuskpäls',
    category: ['dekoration', 'all'],
  },
  {
    name: 'Veteranbil',
    id: 1,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/tomtevagn-1.jpg', ''],
    alt: ['', ''],
    description: 'Fin veteranbil med tomte, i porslin.',
    category: ['dekoration', 'all'],
  },
  {
    name: '',
    id: 2,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/tomtelykta-1.png', ''],
    alt: ['', ''],
    description: 'Gullig svampformad ljuslykta i keramik',
    category: ['dekoration', 'belysning', 'all'],
  },
  {
    name: '',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/ljusstake-vit-1.jpg', ''],
    alt: ['', ''],
    description: 'Ljusstake i vit keramik för 5 ljus',
    category: ['belysning', 'all'],
  },
  {
    name: '',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/ljusstake-gra-1.jpg', ''],
    alt: ['', ''],
    description: 'Ljusstake för 10 ljus i betong',
    category: ['dekoration', 'all'],
  },

  {
    name: '',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/julstjarna-1.png', ''],
    alt: ['', ''],
    description: 'Röd julstjärna 100 cm',
    category: ['dekoration', 'all'],
  },
  {
    name: '',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/julduk-paisely-1.png', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: '',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/julduk-rand-1.png', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: '',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/filt-varg-1.jpg', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: '',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/filt-rutig-1.jpg', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: '',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/kudde-tofsar-1.jpg', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
  {
    name: '',
    id: 3,
    price: 199,
    originalPrice: 199,
    rating: 3,
    amount: 0,
    sum: 0,
    img: ['src/style/shop-imgs/kudde-linne-1.jpg', ''],
    alt: ['', ''],
    description: '',
    category: ['dekoration', 'all'],
  },
];

const productContainer = document.querySelector('.product-container');

for (let i = 0; i < products.length; i++) {
  const product = products[i];
  productContainer.innerHTML += `
    <article class= "xmas-item"
    <h2>${product.name}</h2>
    <img src="${product.img[0]}" alt="" width="200" height="200">
    </article>`;
}
