name: deploy changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      # Steg 1: Checka ut koden från ditt repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Steg 2: Installera Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      # Steg 3: Installera PNPM via NPM
      - name: Install PNPM
        run: npm install -g pnpm@9.12.2

      # Steg 4: Installera beroenden med PNPM
      - name: Install dependencies
        run: pnpm install

      # Steg 5: Bygg projektet
      - name: Build
        run: pnpm run build

      # Steg 6: Deploya till GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
